import { Metadata } from 'next'
import { LegalLayout } from '@/components/legal/legal-layout'
import { LegalPageHeader } from '@/components/legal/legal-page-header'
import { LegalSection } from '@/components/legal/legal-section'
import { ContactSupportBlock } from '@/components/legal/contact-support-block'

export const metadata: Metadata = {
  title: 'Terms of Service | Novelify',
  description: 'Review the terms and conditions governing your use of Novelify, including account registration, intellectual property rights, and accepted use of the platform.',
}

export default function TermsPage() {
  return (
    <LegalLayout>
      <LegalPageHeader
        title="Terms of Service"
        summary="These Terms of Service outline the rules and regulations governing your use of the Novelify platform. By accessing or using Novelify, you agree to be bound by these terms."
        lastUpdated="June 1, 2025"
      />

      <LegalSection title="1. Acceptance of Terms">
        <p style={{ margin: '0 0 12px' }}>
          By creating an account, accessing, or using Novelify (&quot;the Platform&quot;), you agree to be bound by these Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, you may not use the Platform.
        </p>
        <p style={{ margin: 0 }}>
          We reserve the right to update or modify these Terms at any time. Changes will be effective immediately upon posting. Your continued use of the Platform after any changes constitutes acceptance of the revised Terms.
        </p>
      </LegalSection>

      <LegalSection title="2. Account Registration">
        <p style={{ margin: '0 0 12px' }}>
          You must be at least 13 years of age to use Novelify. By registering, you represent that you meet this requirement. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account.
        </p>
        <p style={{ margin: 0 }}>
          You agree to provide accurate, current, and complete information during the registration process and to update such information as needed. Novelify reserves the right to suspend or terminate accounts that violate these Terms or provide false information.
        </p>
      </LegalSection>

      <LegalSection title="3. Subscriptions & Billing">
        <p style={{ margin: '0 0 12px' }}>
          Certain features of Novelify require a paid subscription. Subscription fees, billing cycles, and payment terms are detailed in our Billing Policy. All fees are non-refundable except as expressly stated in our Refund Policy.
        </p>
        <p style={{ margin: 0 }}>
          Novelify may modify subscription fees upon 30 days&apos; notice. Continued use of the Platform after a fee change constitutes acceptance of the new pricing. Failure to pay fees may result in account suspension or termination.
        </p>
      </LegalSection>

      <LegalSection title="4. User Content">
        <p style={{ margin: '0 0 12px' }}>
          You retain full ownership of all manuscripts, outlines, characters, and other creative works (&quot;User Content&quot;) you create or upload to Novelify. We do not claim any intellectual property rights over your User Content.
        </p>
        <p style={{ margin: '0 0 12px' }}>
          By submitting User Content to the Platform, you grant Novelify a limited, non-exclusive license to store, process, and display your content solely for the purpose of providing and improving the Platform&apos;s services. This license terminates when you delete your content or close your account.
        </p>
        <p style={{ margin: 0 }}>
          You represent and warrant that your User Content does not infringe upon any third-party intellectual property rights and complies with all applicable laws.
        </p>
      </LegalSection>

      <LegalSection title="5. AI-Generated Content">
        <p style={{ margin: '0 0 12px' }}>
          Novelify offers AI-powered writing assistance features. Content generated by AI tools is provided as a starting point or suggestion and may contain inaccuracies, biases, or unintended similarities to existing works. You are solely responsible for reviewing, editing, and assuming ownership of any AI-generated content you choose to use.
        </p>
        <p style={{ margin: 0 }}>
          Use of AI features is governed by our AI Usage Policy. Novelify makes no warranties regarding the originality, accuracy, or copyright status of AI-generated content.
        </p>
      </LegalSection>

      <LegalSection title="6. Prohibited Uses">
        <p style={{ margin: '0 0 12px' }}>
          You agree not to use Novelify for any unlawful purpose or in violation of any applicable laws or regulations. Prohibited activities include, but are not limited to:
        </p>
        <ul style={{ margin: '0 0 12px', paddingLeft: 20 }}>
          <li>Uploading or generating content that is illegal, harmful, threatening, abusive, harassing, defamatory, or obscene</li>
          <li>Infringing upon the intellectual property rights of others</li>
          <li>Attempting to gain unauthorized access to the Platform&apos;s systems or other users&apos; accounts</li>
          <li>Using automated scripts, bots, or scrapers to access or manipulate the Platform</li>
          <li>Interfering with the proper functioning of the Platform</li>
        </ul>
        <p style={{ margin: 0 }}>
          Novelify reserves the right to remove any content and suspend or terminate accounts that engage in prohibited uses, at our sole discretion and without prior notice.
        </p>
      </LegalSection>

      <LegalSection title="7. Intellectual Property">
        <p style={{ margin: '0 0 12px' }}>
          The Novelify name, logo, platform design, and all related trademarks, service marks, and trade dress are owned by Novelify. The Platform&apos;s underlying technology, algorithms, and software are protected by copyright, trademark, and other intellectual property laws.
        </p>
        <p style={{ margin: 0 }}>
          You may not reproduce, distribute, modify, create derivative works from, or exploit any portion of the Platform without our express written permission.
        </p>
      </LegalSection>

      <LegalSection title="8. Limitation of Liability">
        <p style={{ margin: '0 0 12px' }}>
          To the maximum extent permitted by law, Novelify shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or relating to your use of the Platform, including but not limited to loss of data, loss of profits, or interruption of service.
        </p>
        <p style={{ margin: 0 }}>
          Our total liability for any claim arising under these Terms shall not exceed the amount you have paid to Novelify in the twelve (12) months preceding the claim.
        </p>
      </LegalSection>

      <LegalSection title="9. Disclaimer of Warranties">
        <p style={{ margin: '0 0 12px' }}>
          Novelify is provided on an &quot;as is&quot; and &quot;as available&quot; basis without warranties of any kind, either express or implied. We do not guarantee that the Platform will be uninterrupted, secure, or error-free, or that any defects will be corrected.
        </p>
        <p style={{ margin: 0 }}>
          We expressly disclaim all warranties, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement.
        </p>
      </LegalSection>

      <LegalSection title="10. Termination">
        <p style={{ margin: '0 0 12px' }}>
          You may terminate your account at any time through your account settings. Upon termination, your access to the Platform will be revoked, and your User Content may be deleted from our servers after a reasonable retention period.
        </p>
        <p style={{ margin: 0 }}>
          Novelify may suspend or terminate your account at any time for violation of these Terms, without liability. Sections pertaining to intellectual property, limitation of liability, and governing law shall survive termination.
        </p>
      </LegalSection>

      <LegalSection title="11. Governing Law">
        <p style={{ margin: 0 }}>
          These Terms shall be governed by and construed in accordance with the laws of the State of Delaware, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be resolved exclusively in the courts of Delaware.
        </p>
      </LegalSection>

      <ContactSupportBlock />
    </LegalLayout>
  )
}
