import { Metadata } from 'next'
import { LegalLayout } from '@/components/legal/legal-layout'
import { LegalPageHeader } from '@/components/legal/legal-page-header'
import { LegalSection } from '@/components/legal/legal-section'
import { ContactSupportBlock } from '@/components/legal/contact-support-block'

export const metadata: Metadata = {
  title: 'AI Usage Policy | Novelify',
  description: 'Learn how Novelify uses AI technology, your rights over AI-generated content, transparency commitments, and the responsible use of AI writing tools.',
}

export default function AIUsagePolicyPage() {
  return (
    <LegalLayout>
      <LegalPageHeader
        title="AI Usage Policy"
        summary="This policy explains how artificial intelligence features work on Novelify, your rights and responsibilities when using AI tools, and our commitment to transparency and responsible AI use."
        lastUpdated="June 1, 2025"
      />

      <LegalSection title="1. Overview">
        <p style={{ margin: '0 0 12px' }}>
          Novelify integrates AI-powered features to assist writers with ideation, outlining, drafting, editing, and overcoming writer&apos;s block. Our AI features are designed to be creative tools that augment your own writing process, not replace it.
        </p>
        <p style={{ margin: 0 }}>
          We use third-party large language models (LLMs) provided by trusted partners, including OpenAI, to power these features. The AI models are continuously improved and may be updated without prior notice.
        </p>
      </LegalSection>

      <LegalSection title="2. How AI Features Work">
        <p style={{ margin: '0 0 12px' }}>
          When you use an AI-powered feature on Novelify, the content you provide (such as a prompt, selected text, or context from your manuscript) is sent to our AI service provider for processing. The generated output is returned to you and displayed within the Platform.
        </p>
        <p style={{ margin: '0 0 12px' }}>
          Examples of AI features include:
        </p>
        <ul style={{ margin: '0 0 12px', paddingLeft: 20 }}>
          <li>AI-assisted writing and text generation</li>
          <li>Plot and character development suggestions</li>
          <li>Grammar, style, and tone analysis</li>
          <li>Chapter summarization and outlining</li>
          <li>Brainstorming and idea generation</li>
        </ul>
        <p style={{ margin: 0 }}>
          The AI may occasionally produce output that is inaccurate, nonsensical, or unintended. You are responsible for reviewing and editing all AI-generated content before publishing or sharing it.
        </p>
      </LegalSection>

      <LegalSection title="3. Ownership of AI-Generated Content">
        <p style={{ margin: '0 0 12px' }}>
          You retain full ownership of any content you create using Novelify&apos;s AI tools, subject to the following:
        </p>
        <ul style={{ margin: '0 0 12px', paddingLeft: 20 }}>
          <li>AI-generated content is provided as a starting point or suggestion and may not be copyrightable in its raw form due to current legal frameworks around AI-generated works</li>
          <li>You are responsible for ensuring that your use of AI-generated content does not infringe upon the rights of others</li>
          <li>Novelify does not claim ownership of any content generated by AI tools on the Platform</li>
        </ul>
        <p style={{ margin: 0 }}>
          We recommend that you meaningfully edit and add your own creative input to any AI-generated content to establish authorship and copyright protection under applicable law.
        </p>
      </LegalSection>

      <LegalSection title="4. Data & Privacy">
        <p style={{ margin: '0 0 12px' }}>
          Your privacy is important to us. When you use AI features:
        </p>
        <ul style={{ margin: '0 0 12px', paddingLeft: 20 }}>
          <li>Prompts and context data sent to AI providers are processed temporarily and are not used to train or improve AI models unless you explicitly opt in</li>
          <li>We have data processing agreements in place with our AI providers that prohibit them from using your data for their own purposes</li>
          <li>Your manuscripts and personal content are not added to public training datasets</li>
        </ul>
        <p style={{ margin: 0 }}>
          For more details, please refer to our Privacy Policy.
        </p>
      </LegalSection>

      <LegalSection title="5. Transparency & Limitations">
        <p style={{ margin: '0 0 12px' }}>
          We are committed to transparency in our use of AI. The following limitations apply:
        </p>
        <ul style={{ margin: '0 0 12px', paddingLeft: 20 }}>
          <li>AI-generated content may contain biases present in the underlying training data</li>
          <li>The AI may occasionally produce content similar to existing copyrighted works due to the nature of training data</li>
          <li>AI features are not a substitute for professional editing, legal advice, or creative judgment</li>
          <li>AI availability and quality may vary based on demand, technical issues, or provider changes</li>
        </ul>
        <p style={{ margin: 0 }}>
          We clearly label AI-generated suggestions within the interface so you can make informed decisions about their use.
        </p>
      </LegalSection>

      <LegalSection title="6. Prohibited Uses of AI">
        <p style={{ margin: '0 0 12px' }}>
          The following uses of Novelify&apos;s AI features are strictly prohibited:
        </p>
        <ul style={{ margin: '0 0 12px', paddingLeft: 20 }}>
          <li>Generating content that is illegal, harmful, discriminatory, or violates our Terms of Service</li>
          <li>Attempting to reverse-engineer, extract, or replicate the underlying AI models</li>
          <li>Using AI features to spam, scam, or deceive others</li>
          <li>Automating AI requests at a volume that degrades service for other users</li>
          <li>Using AI to generate content that infringes on the intellectual property of others</li>
        </ul>
        <p style={{ margin: 0 }}>
          Violation of these prohibitions may result in suspension or termination of your account.
        </p>
      </LegalSection>

      <LegalSection title="7. Fair Use & Rate Limits">
        <p style={{ margin: '0 0 12px' }}>
          To ensure fair access for all users, AI features are subject to rate limits and usage quotas based on your subscription plan. These limits are clearly displayed in your account settings.
        </p>
        <p style={{ margin: 0 }}>
          We reserve the right to adjust rate limits and quotas to maintain service quality and prevent abuse. Excessive or abusive use of AI features may result in temporary throttling or restriction.
        </p>
      </LegalSection>

      <LegalSection title="8. Disclaimer">
        <p style={{ margin: '0' }}>
          AI-assisted writing features are provided &quot;as is&quot; without warranty of any kind. Novelify makes no guarantees regarding the accuracy, originality, completeness, or usefulness of AI-generated content. You assume all risks associated with using AI-generated content, including any claims of copyright infringement or inaccuracy.
        </p>
      </LegalSection>

      <ContactSupportBlock />
    </LegalLayout>
  )
}
